name: Publish image to ghcr.io
on: [workflow_dispatch]

jobs:
  publish_image:
  runs-on: ubuntu:xenial
  steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: build
      run: |
        docker build. -t ghcr.io/chosomeister/socks5-docker:latest
    - name: publish
      run: |
        docker login -u brianmm02 -p ${{ secrets.GGHCR_TOKEN }}
        docker push ghcr.io/chosomeister/socks5-docker:latest
